data=[
{"quote": " Learn to light a candle in the darkest moments of someone\u2019s life. Be the light that helps others see; it is what gives life its deepest significance. ", "by": "Roy T. Bennett"},
{"quote": " Nothing in nature is unbeautiful. ", "by": "Alfred, Lord Tennyson"},
{"quote": " You miss 100% of the shots you don\u2019t take. ", "by": "Wayne Gretzky"},
{"quote": " The butterfly counts not months but moments, and has time enough. ", "by": "Rabindranath Tagore"},
{"quote": " You have survived, EVERY SINGLE bad day so far. ", "by": "Anonymous"},
{"quote": " You're not going to master the rest of your life in one day. Just relax. Master the day. Than just keep doing that every day. ", "by": "Anonymous"},
{"quote": " Silence is the language of God, all else is poor translation. ", "by": "Rumi"},
{"quote": " You miss 100% of the shots you don\u2019t take. ", "by": "Wayne Gretzky"},
{"quote": " You have to expect things of yourself before you can do them. ", "by": "Michael Jordan"},
{"quote": " You're not going to master the rest of your life in one day. Just relax. Master the day. Than just keep doing that every day. ", "by": "Anonymous"},
{"quote": " The beauty of a living thing is not the atoms that go into it, but the way those atoms are put together. ", "by": "Carl Sagan"},
{"quote": " Life is not meant to be easy, my child; but take courage: it can be delightful. ", "by": "George Bernard Shaw"},
{"quote": " This being human is a guest house. Every morning is a new arrival. A joy, a depression, a meanness, some momentary awareness comes as an unexpected visitor...Welcome and entertain them all. Treat each guest honorably. The dark thought, the shame, the malice, meet them at the door laughing, and invite them in. Be grateful for whoever comes, because each has been sent as a guide from beyond. ", "by": "Rumi"},
{"quote": " When you talk, you are only repeating what you already know. But if you listen, you may learn something new. ", "by": "Dalai Lama"},
{"quote": " No amount of guilt can solve the past, and no amount of anxiety can change the future. ", "by": "Anonymous"},
{"quote": " Be who you needed when you were younger. ", "by": "Anonymous"},
{"quote": " Nothing in nature is unbeautiful. ", "by": "Alfred, Lord Tennyson"},
{"quote": " Pretending to not be afraid is as good as actually not being afraid. ", "by": "David Letterman"},
{"quote": " Before you speak, let your words pass through three gates: Is it true? Is it necessary? Is it kind? ", "by": "Rumi"},
{"quote": " Just as there is no loss of basic energy in the universe, so no thought or action is without its effects, present or ultimate, seen or unseen, felt or unfelt. ", "by": "Norman Cousins"},
{"quote": " Be grateful for whoever comes, because each has been sent as a guide from beyond. ", "by": "Rumi"},
{"quote": " When you do things from your soul, you feel a river moving in you, a joy. ", "by": "Rumi"},
{"quote": " Suffering is a gift. In it is hidden mercy. ", "by": "Rumi"},
{"quote": " The wound is the place where the Light enters you. ", "by": "Rumi"},
{"quote": " Learning never exhausts the mind. ", "by": "Leonardo da Vinci"},
{"quote": " Open your mouth only if what you are going to say is more beautiful than the silience. ", "by": "BUDDHA"},
{"quote": " Almost everything will work again if you unplug it for a few minutes, including you. ", "by": "Anne Lamott"},
{"quote": " Suffering is a gift. In it is hidden mercy. ", "by": "Rumi"},
{"quote": " Learn to light a candle in the darkest moments of someone\u2019s life. Be the light that helps others see; it is what gives life its deepest significance. ", "by": "Roy T. Bennett"},
{"quote": " Knock, And He'll open the door. Vanish, And He'll make you shine like the sun. Fall, And He'll raise you to the heavens. Become nothing, And He'll turn you into everything. ", "by": "Rumi"},
{"quote": " Keep your face always toward the sunshine - and shadows will fall behind you. ", "by": "Walt Whitman"},
{"quote": " The only limits you see are the ones you impose on yourself. ", "by": "Dr. Wayne Dyer"},
{"quote": " Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying, \"I will try again tomorrow.\" ", "by": "Mary Anne Radmacher"},
{"quote": " Make yourself a priority once in a while. It's not selfish. It's necessary. ", "by": "Anonymous"},
{"quote": " If your life's work can be accomplished in your lifetime, you're not thinking big enough. ", "by": "Wes Jackson"},
{"quote": " If your life's work can be accomplished in your lifetime, you're not thinking big enough. ", "by": "Wes Jackson"},
{"quote": " Those who bring sunshine to the lives of others cannot keep it from themselves. ", "by": "J. M. Barrie"},
{"quote": " Come let us be friends for once. Let us make life easy on us. Let us be loved ones and lovers. The earth shall be left to no one. ", "by": "Yunus Emre"},
{"quote": " I cannot do all the good that the world needs, but the world needs all the good that I can do. ", "by": "Jana Stanfield"},
{"quote": " Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it. ", "by": "Rumi"},
{"quote": " Come let us be friends for once. Let us make life easy on us. Let us be loved ones and lovers. The earth shall be left to no one. ", "by": "Yunus Emre"},
{"quote": " Goodbyes are only for those who love with their eyes. Because for those who love with heart and soul there is no such thing as separation. ", "by": "Rumi"}
,
{"quote": " Just as there is no loss of basic energy in the universe, so no thought or action is without its effects, present or ultimate, seen or unseen, felt or unfelt. ", "by": "Norman Cousins"},
{"quote": " Pretending to not be afraid is as good as actually not being afraid. ", "by": "David Letterman"},
{"quote": " Be grateful for whoever comes, because each has been sent as a guide from beyond. ", "by": "Rumi"},
{"quote": " The best time to plant a tree was 20 years ago. The second best time is now. ", "by": "Chinese Proverb"},
{"quote": " The greatest of richness is the richness of the soul. ", "by": "Prophet Muhammad (Peace be upon him)"},
{"quote": " It always seems impossible until it is done. ", "by": "Nelson Mandela"},
{"quote": " Keep your face always toward the sunshine - and shadows will fall behind you. ", "by": "Walt Whitman"},
{"quote": " Don't count the days, make the days count. ", "by": "Muhammad Ali"},
{"quote": " Don't fear change. The surprise is the only way to new discoveries. Be playful! ", "by": "Gordana Biernat"},
{"quote": " Everything in the universe is within you. Ask all from yourself. ", "by": "Rumi"},
{"quote": " Life is not meant to be easy, my child; but take courage: it can be delightful. ", "by": "George Bernard Shaw"},
{"quote": " If your life's work can be accomplished in your lifetime, you're not thinking big enough. ", "by": "Wes Jackson"},
{"quote": " Your big opportunity may be right where you are now. ", "by": "Napoleon Hill"},
{"quote": " The only limits you see are the ones you impose on yourself. ", "by": "Dr. Wayne Dyer"},
{"quote": " The happiest people don't have the best of everything, they just make the best of everything. ", "by": "Anonymous"},
{"quote": " We can't help everyone, but everyone can help someone. ", "by": "Ronald Reagan"},
{"quote": " Knock, And He'll open the door. Vanish, And He'll make you shine like the sun. Fall, And He'll raise you to the heavens. Become nothing, And He'll turn you into everything. ", "by": "Rumi"},
{"quote": " Happiness doesn't result from what we get, but from what we give. ", "by": "Ben Carson"},
{"quote": " You're not going to master the rest of your life in one day. Just relax. Master the day. Than just keep doing that every day. ", "by": "Anonymous"},
{"quote": " The happiest people don't have the best of everything, they just make the best of everything. ", "by": "Anonymous"},
{"quote": " Silence is the language of God, all else is poor translation. ", "by": "Rumi"}
,
{"quote": " Love only grows by sharing. You can only have more for yourself by giving it away to others. ", "by": "Brian Tracy"},
{"quote": " Be who you needed when you were younger. ", "by": "Anonymous"},
{"quote": " Be grateful for whoever comes, because each has been sent as a guide from beyond. ", "by": "Rumi"},
{"quote": " Learn to light a candle in the darkest moments of someone\u2019s life. Be the light that helps others see; it is what gives life its deepest significance. ", "by": "Roy T. Bennett"},
{"quote": " Open your mouth only if what you are going to say is more beautiful than the silience. ", "by": "BUDDHA"},
{"quote": " Life isn't about getting and having, it's about giving and being. ", "by": "Kevin Kruse"},
{"quote": " Forget safety. Live where you fear to live. Destroy your reputation. Be notorious. ", "by": "Rumi"},
{"quote": " Goodbyes are only for those who love with their eyes. Because for those who love with heart and soul there is no such thing as separation. ", "by": "Rumi"},
{"quote": " Live as if you were to die tomorrow. Learn as if you were to live forever. ", "by": "Mahatma Gandhi"},
{"quote": " Keep your face always toward the sunshine - and shadows will fall behind you. ", "by": "Walt Whitman"},
{"quote": " Nothing in nature is unbeautiful. ", "by": "Alfred, Lord Tennyson"},
{"quote": " If you want to become full, let yourself be empty. ", "by": "Lao Tzu"},
{"quote": " So many books, so little time. ", "by": "Frank Zappa"},
{"quote": " Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying, \"I will try again tomorrow.\" ", "by": "Mary Anne Radmacher"},
{"quote": " Pretending to not be afraid is as good as actually not being afraid. ", "by": "David Letterman"},
{"quote": " Those who bring sunshine to the lives of others cannot keep it from themselves. ", "by": "J. M. Barrie"},
{"quote": " When you do things from your soul, you feel a river moving in you, a joy. ", "by": "Rumi"},
{"quote": " Live as if you were to die tomorrow. Learn as if you were to live forever. ", "by": "Mahatma Gandhi"},
{"quote": " The happiest people don't have the best of everything, they just make the best of everything. ", "by": "Anonymous"},
{"quote": " Come let us be friends for once. Let us make life easy on us. Let us be loved ones and lovers. The earth shall be left to no one. ", "by": "Yunus Emre"},
{"quote": " Don't ruin a good today by thinking about a bad yesterday. Let it go. ", "by": "Anonymous"}
,
{"quote": " When you talk, you are only repeating what you already know. But if you listen, you may learn something new. ", "by": "Dalai Lama"},
{"quote": " How wonderful it is that nobody need wait a single moment before starting to improve the world. ", "by": "Anne Frank"},
{"quote": " Forget safety. Live where you fear to live. Destroy your reputation. Be notorious. ", "by": "Rumi"},
{"quote": " Come let us be friends for once. Let us make life easy on us. Let us be loved ones and lovers. The earth shall be left to no one. ", "by": "Yunus Emre"},
{"quote": " How wonderful it is that nobody need wait a single moment before starting to improve the world. ", "by": "Anne Frank"},
{"quote": " Come let us be friends for once. Let us make life easy on us. Let us be loved ones and lovers. The earth shall be left to no one. ", "by": "Yunus Emre"},
{"quote": " You're not going to master the rest of your life in one day. Just relax. Master the day. Than just keep doing that every day. ", "by": "Anonymous"},
{"quote": " Live as if you were to die tomorrow. Learn as if you were to live forever. ", "by": "Mahatma Gandhi"},
{"quote": " This being human is a guest house. Every morning is a new arrival. A joy, a depression, a meanness, some momentary awareness comes as an unexpected visitor...Welcome and entertain them all. Treat each guest honorably. The dark thought, the shame, the malice, meet them at the door laughing, and invite them in. Be grateful for whoever comes, because each has been sent as a guide from beyond. ", "by": "Rumi"},
{"quote": " The best time to plant a tree was 20 years ago. The second best time is now. ", "by": "Chinese Proverb"},
{"quote": " The greatest of richness is the richness of the soul. ", "by": "Prophet Muhammad (Peace be upon him)"},
{"quote": " Don't fear change. The surprise is the only way to new discoveries. Be playful! ", "by": "Gordana Biernat"},
{"quote": " Don't ruin a good today by thinking about a bad yesterday. Let it go. ", "by": "Anonymous"},
{"quote": " Do not seek to follow in the footsteps of the wise. Seek what they sought. ", "by": "Matsuo Basho"},
{"quote": " Those who bring sunshine to the lives of others cannot keep it from themselves. ", "by": "J. M. Barrie"},
{"quote": " I cannot do all the good that the world needs, but the world needs all the good that I can do. ", "by": "Jana Stanfield"},
{"quote": " You're not going to master the rest of your life in one day. Just relax. Master the day. Than just keep doing that every day. ", "by": "Anonymous"},
{"quote": " Keep your face always toward the sunshine - and shadows will fall behind you. ", "by": "Walt Whitman"},
{"quote": " Don\u2019t grieve. Anything you lose comes round in another form. ", "by": "Rumi"},
{"quote": " Never wish them pain. That's not who you are. If they caused you pain, they must have pain inside. Wish them healing. ", "by": "Najwa Zebian"},
{"quote": " Pretending to not be afraid is as good as actually not being afraid. ", "by": "David Letterman"}
,
{"quote": " Life isn't about getting and having, it's about giving and being. ", "by": "Kevin Kruse"},
{"quote": " If you want to go quickly, go alone. If you want to go far, go together. ", "by": "African proverb"},
{"quote": " What we think, what we become. ", "by": "Buddha"},
{"quote": " Don't count the days, make the days count. ", "by": "Muhammad Ali"},
{"quote": " At the end of your life, you will never regret not having passed one more test, not winning one more verdict or not closing one more deal. You will regret time not spent with a husband, a friend, a child, or a parent. ", "by": "Barbara Bush"},
{"quote": " What we think, what we become. ", "by": "Buddha"},
{"quote": " We can't help everyone, but everyone can help someone. ", "by": "Ronald Reagan"},
{"quote": " Don't fear change. The surprise is the only way to new discoveries. Be playful! ", "by": "Gordana Biernat"},
{"quote": " The best time to plant a tree was 20 years ago. The second best time is now. ", "by": "Chinese Proverb"},
{"quote": " Kindness, like a boomerang, always returns. ", "by": "Unknown"},
{"quote": " Don't ruin a good today by thinking about a bad yesterday. Let it go. ", "by": "Anonymous"},
{"quote": " Just as there is no loss of basic energy in the universe, so no thought or action is without its effects, present or ultimate, seen or unseen, felt or unfelt. ", "by": "Norman Cousins"},
{"quote": " You have survived, EVERY SINGLE bad day so far. ", "by": "Anonymous"},
{"quote": " If you want to become full, let yourself be empty. ", "by": "Lao Tzu"},
{"quote": " The butterfly counts not months but moments, and has time enough. ", "by": "Rabindranath Tagore"},
{"quote": " It always seems impossible until it is done. ", "by": "Nelson Mandela"},
{"quote": " Make yourself a priority once in a while. It's not selfish. It's necessary. ", "by": "Anonymous"},
{"quote": " You can never cross the ocean unless you have the courage to lose sight of the shore. ", "by": "Andr\u00e8 Gide"},
{"quote": " Don't fear change. The surprise is the only way to new discoveries. Be playful! ", "by": "Gordana Biernat"},
{"quote": " You often feel tired, not because you've done too much, but because you've done too little of what sparks a light in you. ", "by": "Anonymous"},
{"quote": " Forget safety. Live where you fear to live. Destroy your reputation. Be notorious. ", "by": "Rumi"}
,
{"quote": " Almost everything will work again if you unplug it for a few minutes, including you. ", "by": "Anne Lamott"},
{"quote": " If you want to become full, let yourself be empty. ", "by": "Lao Tzu"},
{"quote": " No amount of guilt can solve the past, and no amount of anxiety can change the future. ", "by": "Anonymous"},
{"quote": " Be who you needed when you were younger. ", "by": "Anonymous"},
{"quote": " You have to expect things of yourself before you can do them. ", "by": "Michael Jordan"},
{"quote": " Don\u2019t grieve. Anything you lose comes round in another form. ", "by": "Rumi"},
{"quote": " When you talk, you are only repeating what you already know. But if you listen, you may learn something new. ", "by": "Dalai Lama"},
{"quote": " When you do things from your soul, you feel a river moving in you, a joy. ", "by": "Rumi"},
{"quote": " Never wish them pain. That's not who you are. If they caused you pain, they must have pain inside. Wish them healing. ", "by": "Najwa Zebian"},
{"quote": " What you seek is seeking you. ", "by": "Rumi"},
{"quote": " Seek knowledge from cradle to the grave. ", "by": "Prophet Muhammad (Peace be upon him)"},
{"quote": " Don\u2019t grieve. Anything you lose comes round in another form. ", "by": "Rumi"},
{"quote": " Suffering is a gift. In it is hidden mercy. ", "by": "Rumi"},
{"quote": " The beauty of a living thing is not the atoms that go into it, but the way those atoms are put together. ", "by": "Carl Sagan"},
{"quote": " We may have all come on different ships, but we're in the same boat now. ", "by": "M.L.King"},
{"quote": " And you? When will you begin that long journey into yourself? ", "by": "Rumi"},
{"quote": " Open your mouth only if what you are going to say is more beautiful than the silience. ", "by": "BUDDHA"},
{"quote": " Your big opportunity may be right where you are now. ", "by": "Napoleon Hill"},
{"quote": " Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying, \"I will try again tomorrow.\" ", "by": "Mary Anne Radmacher"},
{"quote": " Your big opportunity may be right where you are now. ", "by": "Napoleon Hill"},
{"quote": " Just as there is no loss of basic energy in the universe, so no thought or action is without its effects, present or ultimate, seen or unseen, felt or unfelt. ", "by": "Norman Cousins"}
,
{"quote": " Don't ruin a good today by thinking about a bad yesterday. Let it go. ", "by": "Anonymous"},
{"quote": " You have survived, EVERY SINGLE bad day so far. ", "by": "Anonymous"},
{"quote": " Forget safety. Live where you fear to live. Destroy your reputation. Be notorious. ", "by": "Rumi"},
{"quote": " Come let us be friends for once. Let us make life easy on us. Let us be loved ones and lovers. The earth shall be left to no one. ", "by": "Yunus Emre"},
{"quote": " Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying, \"I will try again tomorrow.\" ", "by": "Mary Anne Radmacher"},
{"quote": " Nothing in nature is unbeautiful. ", "by": "Alfred, Lord Tennyson"},
{"quote": " Kindness, like a boomerang, always returns. ", "by": "Unknown"},
{"quote": " We can't help everyone, but everyone can help someone. ", "by": "Ronald Reagan"},
{"quote": " No amount of guilt can solve the past, and no amount of anxiety can change the future. ", "by": "Anonymous"},
{"quote": " I tried to make sense of the Four Books, until love arrived, and it all became a single syllable. ", "by": "Yunus Emre"},
{"quote": " I tried to make sense of the Four Books, until love arrived, and it all became a single syllable. ", "by": "Yunus Emre"},
{"quote": " Sorrow prepares you for joy. It violently sweeps everything out of your house, so that new joy can find space to enter. It shakes the yellow leaves from the bough of your heart, so that fresh, green leaves can grow in their place. It pulls up the rotten roots, so that new roots hidden beneath have room to grow. Whatever sorrow shakes from your heart, far better things will take their place. ", "by": "Rumi"},
{"quote": " Love only grows by sharing. You can only have more for yourself by giving it away to others. ", "by": "Brian Tracy"},
{"quote": " Every block of stone has a statue inside it and it is the task of the sculptor to discover it. ", "by": "Michelangelo"},
{"quote": " Where there is ruin, there is hope for a treasure. ", "by": "Rumi"},
{"quote": " It always seems impossible until it is done. ", "by": "Nelson Mandela"},
{"quote": " Life is not meant to be easy, my child; but take courage: it can be delightful. ", "by": "George Bernard Shaw"},
{"quote": " Never let your sense of morals prevent you from doing what is right. ", "by": "Isaac Asimov"},
{"quote": " Be who you needed when you were younger. ", "by": "Anonymous"},
{"quote": " I tried to make sense of the Four Books, until love arrived, and it all became a single syllable. ", "by": "Yunus Emre"},
{"quote": " You're not going to master the rest of your life in one day. Just relax. Master the day. Than just keep doing that every day. ", "by": "Anonymous"},
{"quote": " This being human is a guest house. Every morning is a new arrival. A joy, a depression, a meanness, some momentary awareness comes as an unexpected visitor...Welcome and entertain them all. Treat each guest honorably. The dark thought, the shame, the malice, meet them at the door laughing, and invite them in. Be grateful for whoever comes, because each has been sent as a guide from beyond. ", "by": "Rumi"},
{"quote": " Be like the sun for grace and mercy. Be like the night to cover others' faults. Be like running water for generosity. Be like death for rage and anger. Be like the Earth for modesty. Appear as you are. Be as you appear. ", "by": "Rumi"},
{"quote": " Keep your face always toward the sunshine - and shadows will fall behind you. ", "by": "Walt Whitman"},
{"quote": " Don't ruin a good today by thinking about a bad yesterday. Let it go. ", "by": "Anonymous"},
{"quote": " I want to sing like the birds sing, not worrying about who hears or what they think. ", "by": "Rumi"},
{"quote": " When you talk, you are only repeating what you already know. But if you listen, you may learn something new. ", "by": "Dalai Lama"},
{"quote": " Make yourself a priority once in a while. It's not selfish. It's necessary. ", "by": "Anonymous"},
{"quote": " Respond to every call that excites your spirit. ", "by": "Rumi"},
{"quote": " Be like the sun for grace and mercy. Be like the night to cover others' faults. Be like running water for generosity. Be like death for rage and anger. Be like the Earth for modesty. Appear as you are. Be as you appear. ", "by": "Rumi"},
{"quote": " Learning never exhausts the mind. ", "by": "Leonardo da Vinci"}
,
{"quote": " You're not going to master the rest of your life in one day. Just relax. Master the day. Than just keep doing that every day. ", "by": "Anonymous"},
{"quote": " When you do things from your soul, you feel a river moving in you, a joy. ", "by": "Rumi"},
{"quote": " Every block of stone has a statue inside it and it is the task of the sculptor to discover it. ", "by": "Michelangelo"},
{"quote": " Be grateful for whoever comes, because each has been sent as a guide from beyond. ", "by": "Rumi"},
{"quote": " Learning never exhausts the mind. ", "by": "Leonardo da Vinci"},
{"quote": " You have to expect things of yourself before you can do them. ", "by": "Michael Jordan"},
{"quote": " In the end only three things matter: how much you loved, how gently you lived, and how gracefully you let go of things not meant for you. ", "by": "Anonymous"},
{"quote": " Don't be satisfied with stories, how things have gone with others. Unfold your own myth. ", "by": "Rumi"},
{"quote": " You have to expect things of yourself before you can do them. ", "by": "Michael Jordan"},
{"quote": " I tried to make sense of the Four Books, until love arrived, and it all became a single syllable. ", "by": "Yunus Emre"},
{"quote": " Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it. ", "by": "Rumi"},
{"quote": " If you are irritated by every rub, how will your mirror be polished? ", "by": "Rumi"},
{"quote": " Respond to every call that excites your spirit. ", "by": "Rumi"},
{"quote": " Never let your sense of morals prevent you from doing what is right. ", "by": "Isaac Asimov"},
{"quote": " What you seek is seeking you. ", "by": "Rumi"},
{"quote": " We may have all come on different ships, but we're in the same boat now. ", "by": "M.L.King"},
{"quote": " Never let your sense of morals prevent you from doing what is right. ", "by": "Isaac Asimov"},
{"quote": " Everything in the universe is within you. Ask all from yourself. ", "by": "Rumi"},
{"quote": " The beauty of a living thing is not the atoms that go into it, but the way those atoms are put together. ", "by": "Carl Sagan"},
{"quote": " Don't be satisfied with stories, how things have gone with others. Unfold your own myth. ", "by": "Rumi"},
{"quote": " Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying, \"I will try again tomorrow.\" ", "by": "Mary Anne Radmacher"},
{"quote": " No amount of guilt can solve the past, and no amount of anxiety can change the future. ", "by": "Anonymous"},
{"quote": " I cannot do all the good that the world needs, but the world needs all the good that I can do. ", "by": "Jana Stanfield"},
{"quote": " Suffering is a gift. In it is hidden mercy. ", "by": "Rumi"},
{"quote": " No amount of guilt can solve the past, and no amount of anxiety can change the future. ", "by": "Anonymous"},
{"quote": " Be like the sun for grace and mercy. Be like the night to cover others' faults. Be like running water for generosity. Be like death for rage and anger. Be like the Earth for modesty. Appear as you are. Be as you appear. ", "by": "Rumi"},
{"quote": " Stop acting so small. You are the universe in ecstatic motion. ", "by": "Rumi"},
{"quote": " Respond to every call that excites your spirit. ", "by": "Rumi"},
{"quote": " I tried to make sense of the Four Books, until love arrived, and it all became a single syllable. ", "by": "Yunus Emre"},
{"quote": " The best time to plant a tree was 20 years ago. The second best time is now. ", "by": "Chinese Proverb"},
{"quote": " The best time to plant a tree was 20 years ago. The second best time is now. ", "by": "Chinese Proverb"},
{"quote": " At the end of your life, you will never regret not having passed one more test, not winning one more verdict or not closing one more deal. You will regret time not spent with a husband, a friend, a child, or a parent. ", "by": "Barbara Bush"}
,
{"quote": " When you do things from your soul, you feel a river moving in you, a joy. ", "by": "Rumi"},
{"quote": " Don't count the days, make the days count. ", "by": "Muhammad Ali"},
{"quote": " Everything in the universe is within you. Ask all from yourself. ", "by": "Rumi"},
{"quote": " We may have all come on different ships, but we're in the same boat now. ", "by": "M.L.King"},
{"quote": " In the end only three things matter: how much you loved, how gently you lived, and how gracefully you let go of things not meant for you. ", "by": "Anonymous"},
{"quote": " Almost everything will work again if you unplug it for a few minutes, including you. ", "by": "Anne Lamott"},
{"quote": " Open your mouth only if what you are going to say is more beautiful than the silience. ", "by": "BUDDHA"},
{"quote": " Be grateful for whoever comes, because each has been sent as a guide from beyond. ", "by": "Rumi"},
{"quote": " Everything in the universe is within you. Ask all from yourself. ", "by": "Rumi"},
{"quote": " Forget safety. Live where you fear to live. Destroy your reputation. Be notorious. ", "by": "Rumi"},
{"quote": " And you? When will you begin that long journey into yourself? ", "by": "Rumi"},
{"quote": " Raise your words, not voice. It is rain that grows flowers, not thunder. ", "by": "Rumi"},
{"quote": " Open your mouth only if what you are going to say is more beautiful than the silience. ", "by": "BUDDHA"},
{"quote": " Live as if you were to die tomorrow. Learn as if you were to live forever. ", "by": "Mahatma Gandhi"},
{"quote": " Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it. ", "by": "Rumi"},
{"quote": " Life isn't about getting and having, it's about giving and being. ", "by": "Kevin Kruse"},
{"quote": " Be who you needed when you were younger. ", "by": "Anonymous"},
{"quote": " When you talk, you are only repeating what you already know. But if you listen, you may learn something new. ", "by": "Dalai Lama"},
{"quote": " Almost everything will work again if you unplug it for a few minutes, including you. ", "by": "Anne Lamott"},
{"quote": " So many books, so little time. ", "by": "Frank Zappa"},
{"quote": " Come let us be friends for once. Let us make life easy on us. Let us be loved ones and lovers. The earth shall be left to no one. ", "by": "Yunus Emre"},
{"quote": " I cannot do all the good that the world needs, but the world needs all the good that I can do. ", "by": "Jana Stanfield"},
{"quote": " What you seek is seeking you. ", "by": "Rumi"},
{"quote": " You can never cross the ocean unless you have the courage to lose sight of the shore. ", "by": "Andr\u00e8 Gide"},
{"quote": " Be grateful for whoever comes, because each has been sent as a guide from beyond. ", "by": "Rumi"},
{"quote": " I tried to make sense of the Four Books, until love arrived, and it all became a single syllable. ", "by": "Yunus Emre"},
{"quote": " When you talk, you are only repeating what you already know. But if you listen, you may learn something new. ", "by": "Dalai Lama"},
{"quote": " The happiest people don't have the best of everything, they just make the best of everything. ", "by": "Anonymous"},
{"quote": " This being human is a guest house. Every morning is a new arrival. A joy, a depression, a meanness, some momentary awareness comes as an unexpected visitor...Welcome and entertain them all. Treat each guest honorably. The dark thought, the shame, the malice, meet them at the door laughing, and invite them in. Be grateful for whoever comes, because each has been sent as a guide from beyond. ", "by": "Rumi"},
{"quote": " So many books, so little time. ", "by": "Frank Zappa"},
{"quote": " This being human is a guest house. Every morning is a new arrival. A joy, a depression, a meanness, some momentary awareness comes as an unexpected visitor...Welcome and entertain them all. Treat each guest honorably. The dark thought, the shame, the malice, meet them at the door laughing, and invite them in. Be grateful for whoever comes, because each has been sent as a guide from beyond. ", "by": "Rumi"}
,
{"quote": " Happiness doesn't result from what we get, but from what we give. ", "by": "Ben Carson"},
{"quote": " Where there is ruin, there is hope for a treasure. ", "by": "Rumi"},
{"quote": " No amount of guilt can solve the past, and no amount of anxiety can change the future. ", "by": "Anonymous"},
{"quote": " Do not seek to follow in the footsteps of the wise. Seek what they sought. ", "by": "Matsuo Basho"},
{"quote": " In the end only three things matter: how much you loved, how gently you lived, and how gracefully you let go of things not meant for you. ", "by": "Anonymous"},
{"quote": " Be who you needed when you were younger. ", "by": "Anonymous"},
{"quote": " We must be willing to let go of the life we have planned, so as to have the life that is waiting for us. ", "by": "E. M. Forster"},
{"quote": " Come let us be friends for once. Let us make life easy on us. Let us be loved ones and lovers. The earth shall be left to no one. ", "by": "Yunus Emre"},
{"quote": " Raise your words, not voice. It is rain that grows flowers, not thunder. ", "by": "Rumi"},
{"quote": " So many books, so little time. ", "by": "Frank Zappa"},
{"quote": " If your life's work can be accomplished in your lifetime, you're not thinking big enough. ", "by": "Wes Jackson"},
{"quote": " At the end of your life, you will never regret not having passed one more test, not winning one more verdict or not closing one more deal. You will regret time not spent with a husband, a friend, a child, or a parent. ", "by": "Barbara Bush"},
{"quote": " You have to expect things of yourself before you can do them. ", "by": "Michael Jordan"},
{"quote": " Respond to every call that excites your spirit. ", "by": "Rumi"},
{"quote": " I want to sing like the birds sing, not worrying about who hears or what they think. ", "by": "Rumi"},
{"quote": " We must be willing to let go of the life we have planned, so as to have the life that is waiting for us. ", "by": "E. M. Forster"},
{"quote": " I tried to make sense of the Four Books, until love arrived, and it all became a single syllable. ", "by": "Yunus Emre"},
{"quote": " You can never cross the ocean unless you have the courage to lose sight of the shore. ", "by": "Andr\u00e8 Gide"},
{"quote": " Learn to light a candle in the darkest moments of someone\u2019s life. Be the light that helps others see; it is what gives life its deepest significance. ", "by": "Roy T. Bennett"},
{"quote": " Forget safety. Live where you fear to live. Destroy your reputation. Be notorious. ", "by": "Rumi"},
{"quote": " The only limits you see are the ones you impose on yourself. ", "by": "Dr. Wayne Dyer"},
{"quote": " If you feel beautiful, then you are. Even if you don't, you still are. ", "by": "Terri Guillemets"},
{"quote": " Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it. ", "by": "Rumi"},
{"quote": " This being human is a guest house. Every morning is a new arrival. A joy, a depression, a meanness, some momentary awareness comes as an unexpected visitor...Welcome and entertain them all. Treat each guest honorably. The dark thought, the shame, the malice, meet them at the door laughing, and invite them in. Be grateful for whoever comes, because each has been sent as a guide from beyond. ", "by": "Rumi"},
{"quote": " Your big opportunity may be right where you are now. ", "by": "Napoleon Hill"},
{"quote": " What we think, what we become. ", "by": "Buddha"},
{"quote": " Open your mouth only if what you are going to say is more beautiful than the silience. ", "by": "BUDDHA"},
{"quote": " In the end only three things matter: how much you loved, how gently you lived, and how gracefully you let go of things not meant for you. ", "by": "Anonymous"},
{"quote": " Forget safety. Live where you fear to live. Destroy your reputation. Be notorious. ", "by": "Rumi"},
{"quote": " You're not going to master the rest of your life in one day. Just relax. Master the day. Than just keep doing that every day. ", "by": "Anonymous"},
{"quote": " Be like the sun for grace and mercy. Be like the night to cover others' faults. Be like running water for generosity. Be like death for rage and anger. Be like the Earth for modesty. Appear as you are. Be as you appear. ", "by": "Rumi"}
,
{"quote": " Don't ruin a good today by thinking about a bad yesterday. Let it go. ", "by": "Anonymous"},
{"quote": " Never wish them pain. That's not who you are. If they caused you pain, they must have pain inside. Wish them healing. ", "by": "Najwa Zebian"},
{"quote": " Don't count the days, make the days count. ", "by": "Muhammad Ali"},
{"quote": " Ego says, \"Once everything falls into place, I'll feel peace.\" Spirit says \"Find your peace, and then everything will fall into place.\" ", "by": "Marianne Williamson"},
{"quote": " Life is not meant to be easy, my child; but take courage: it can be delightful. ", "by": "George Bernard Shaw"},
{"quote": " Life is not meant to be easy, my child; but take courage: it can be delightful. ", "by": "George Bernard Shaw"},
{"quote": " The happiest people don't have the best of everything, they just make the best of everything. ", "by": "Anonymous"},
{"quote": " Every block of stone has a statue inside it and it is the task of the sculptor to discover it. ", "by": "Michelangelo"},
{"quote": " You're not going to master the rest of your life in one day. Just relax. Master the day. Than just keep doing that every day. ", "by": "Anonymous"},
{"quote": " Don't be satisfied with stories, how things have gone with others. Unfold your own myth. ", "by": "Rumi"},
{"quote": " Make yourself a priority once in a while. It's not selfish. It's necessary. ", "by": "Anonymous"},
{"quote": " Don't fear change. The surprise is the only way to new discoveries. Be playful! ", "by": "Gordana Biernat"},
{"quote": " In the end only three things matter: how much you loved, how gently you lived, and how gracefully you let go of things not meant for you. ", "by": "Anonymous"},
{"quote": " If you want to become full, let yourself be empty. ", "by": "Lao Tzu"},
{"quote": " Where there is ruin, there is hope for a treasure. ", "by": "Rumi"},
{"quote": " Do not seek to follow in the footsteps of the wise. Seek what they sought. ", "by": "Matsuo Basho"},
{"quote": " No amount of guilt can solve the past, and no amount of anxiety can change the future. ", "by": "Anonymous"},
{"quote": " Don't fear change. The surprise is the only way to new discoveries. Be playful! ", "by": "Gordana Biernat"},
{"quote": " Don\u2019t grieve. Anything you lose comes round in another form. ", "by": "Rumi"},
{"quote": " Don\u2019t grieve. Anything you lose comes round in another form. ", "by": "Rumi"},
{"quote": " If your life's work can be accomplished in your lifetime, you're not thinking big enough. ", "by": "Wes Jackson"},
{"quote": " What you seek is seeking you. ", "by": "Rumi"},
{"quote": " Happiness doesn't result from what we get, but from what we give. ", "by": "Ben Carson"},
{"quote": " Never wish them pain. That's not who you are. If they caused you pain, they must have pain inside. Wish them healing. ", "by": "Najwa Zebian"},
{"quote": " This being human is a guest house. Every morning is a new arrival. A joy, a depression, a meanness, some momentary awareness comes as an unexpected visitor...Welcome and entertain them all. Treat each guest honorably. The dark thought, the shame, the malice, meet them at the door laughing, and invite them in. Be grateful for whoever comes, because each has been sent as a guide from beyond. ", "by": "Rumi"},
{"quote": " Ego says, \"Once everything falls into place, I'll feel peace.\" Spirit says \"Find your peace, and then everything will fall into place.\" ", "by": "Marianne Williamson"},
{"quote": " If you are irritated by every rub, how will your mirror be polished? ", "by": "Rumi"},
{"quote": " Don\u2019t grieve. Anything you lose comes round in another form. ", "by": "Rumi"},
{"quote": " Just as there is no loss of basic energy in the universe, so no thought or action is without its effects, present or ultimate, seen or unseen, felt or unfelt. ", "by": "Norman Cousins"},
{"quote": " Life isn't about getting and having, it's about giving and being. ", "by": "Kevin Kruse"},
{"quote": " Forget safety. Live where you fear to live. Destroy your reputation. Be notorious. ", "by": "Rumi"},
{"quote": " The wound is the place where the Light enters you. ", "by": "Rumi"}
,
{"quote": " Don\u2019t grieve. Anything you lose comes round in another form. ", "by": "Rumi"},
{"quote": " The greatest of richness is the richness of the soul. ", "by": "Prophet Muhammad (Peace be upon him)"},
{"quote": " If you are irritated by every rub, how will your mirror be polished? ", "by": "Rumi"},
{"quote": " The greatest of richness is the richness of the soul. ", "by": "Prophet Muhammad (Peace be upon him)"},
{"quote": " Ego says, \"Once everything falls into place, I'll feel peace.\" Spirit says \"Find your peace, and then everything will fall into place.\" ", "by": "Marianne Williamson"},
{"quote": " Life is not meant to be easy, my child; but take courage: it can be delightful. ", "by": "George Bernard Shaw"},
{"quote": " Don't fear change. The surprise is the only way to new discoveries. Be playful! ", "by": "Gordana Biernat"},
{"quote": " Make yourself a priority once in a while. It's not selfish. It's necessary. ", "by": "Anonymous"},
{"quote": " The only limits you see are the ones you impose on yourself. ", "by": "Dr. Wayne Dyer"},
{"quote": " Don't count the days, make the days count. ", "by": "Muhammad Ali"},
{"quote": " Open your mouth only if what you are going to say is more beautiful than the silience. ", "by": "BUDDHA"},
{"quote": " Never wish them pain. That's not who you are. If they caused you pain, they must have pain inside. Wish them healing. ", "by": "Najwa Zebian"},
{"quote": " Where there is ruin, there is hope for a treasure. ", "by": "Rumi"},
{"quote": " I tried to make sense of the Four Books, until love arrived, and it all became a single syllable. ", "by": "Yunus Emre"},
{"quote": " Happiness doesn't result from what we get, but from what we give. ", "by": "Ben Carson"},
{"quote": " Be who you needed when you were younger. ", "by": "Anonymous"},
{"quote": " I tried to make sense of the Four Books, until love arrived, and it all became a single syllable. ", "by": "Yunus Emre"},
{"quote": " Make yourself a priority once in a while. It's not selfish. It's necessary. ", "by": "Anonymous"},
{"quote": " Live as if you were to die tomorrow. Learn as if you were to live forever. ", "by": "Mahatma Gandhi"},
{"quote": " Stop acting so small. You are the universe in ecstatic motion. ", "by": "Rumi"},
{"quote": " Don\u2019t grieve. Anything you lose comes round in another form. ", "by": "Rumi"},
{"quote": " Don\u2019t grieve. Anything you lose comes round in another form. ", "by": "Rumi"},
{"quote": " Keep your face always toward the sunshine - and shadows will fall behind you. ", "by": "Walt Whitman"},
{"quote": " We may have all come on different ships, but we're in the same boat now. ", "by": "M.L.King"},
{"quote": " At the end of your life, you will never regret not having passed one more test, not winning one more verdict or not closing one more deal. You will regret time not spent with a husband, a friend, a child, or a parent. ", "by": "Barbara Bush"},
{"quote": " When you talk, you are only repeating what you already know. But if you listen, you may learn something new. ", "by": "Dalai Lama"},
{"quote": " You can never cross the ocean unless you have the courage to lose sight of the shore. ", "by": "Andr\u00e8 Gide"},
{"quote": " Don\u2019t grieve. Anything you lose comes round in another form. ", "by": "Rumi"},
{"quote": " If you are irritated by every rub, how will your mirror be polished? ", "by": "Rumi"},
{"quote": " Be who you needed when you were younger. ", "by": "Anonymous"},
{"quote": " This being human is a guest house. Every morning is a new arrival. A joy, a depression, a meanness, some momentary awareness comes as an unexpected visitor...Welcome and entertain them all. Treat each guest honorably. The dark thought, the shame, the malice, meet them at the door laughing, and invite them in. Be grateful for whoever comes, because each has been sent as a guide from beyond. ", "by": "Rumi"}
,
{"quote": " You miss 100% of the shots you don\u2019t take. ", "by": "Wayne Gretzky"},
{"quote": " What we think, what we become. ", "by": "Buddha"},
{"quote": " Kindness, like a boomerang, always returns. ", "by": "Unknown"},
{"quote": " I cannot do all the good that the world needs, but the world needs all the good that I can do. ", "by": "Jana Stanfield"},
{"quote": " We can't help everyone, but everyone can help someone. ", "by": "Ronald Reagan"},
{"quote": " Stop acting so small. You are the universe in ecstatic motion. ", "by": "Rumi"},
{"quote": " Never wish them pain. That's not who you are. If they caused you pain, they must have pain inside. Wish them healing. ", "by": "Najwa Zebian"},
{"quote": " If you feel beautiful, then you are. Even if you don't, you still are. ", "by": "Terri Guillemets"},
{"quote": " Nothing in nature is unbeautiful. ", "by": "Alfred, Lord Tennyson"},
{"quote": " Those who bring sunshine to the lives of others cannot keep it from themselves. ", "by": "J. M. Barrie"},
{"quote": " Don't count the days, make the days count. ", "by": "Muhammad Ali"},
{"quote": " Just as there is no loss of basic energy in the universe, so no thought or action is without its effects, present or ultimate, seen or unseen, felt or unfelt. ", "by": "Norman Cousins"},
{"quote": " The beauty of a living thing is not the atoms that go into it, but the way those atoms are put together. ", "by": "Carl Sagan"},
{"quote": " Learning never exhausts the mind. ", "by": "Leonardo da Vinci"},
{"quote": " Goodbyes are only for those who love with their eyes. Because for those who love with heart and soul there is no such thing as separation. ", "by": "Rumi"},
{"quote": " The greatest of richness is the richness of the soul. ", "by": "Prophet Muhammad (Peace be upon him)"},
{"quote": " What you seek is seeking you. ", "by": "Rumi"},
{"quote": " The best time to plant a tree was 20 years ago. The second best time is now. ", "by": "Chinese Proverb"},
{"quote": " Keep your face always toward the sunshine - and shadows will fall behind you. ", "by": "Walt Whitman"},
{"quote": " The happiest people don't have the best of everything, they just make the best of everything. ", "by": "Anonymous"},
{"quote": " Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying, \"I will try again tomorrow.\" ", "by": "Mary Anne Radmacher"}
]

var count=data.length;
var randomItem=[]
while(count!=0){
randomItem.push( data[Math.floor(Math.random()*data.length)]);
count=count-1;
}


let quotes=document.getElementById("quotes");
let quotesHTMl="";
randomItem.forEach(function(element){
	let paper=`<div class="col col s12 m4">
            <div class="card">
                <div class="card-content">
                    <b>${element["quote"]}</<b>By ${element["by"]}
                </div>
            </div>
        </div>`
quotesHTMl+=paper;

})
quotes.innerHTML=quotesHTMl;